from dotenv import load_dotenv
import os

dotenv_path = "constants/.env"
load_dotenv(dotenv_path)

LOG_DATA_PATH = os.getenv("LOG_DATA_PATH")
LOG_MODEL_PATH = os.getenv("LOG_MODEL_PATH")
LOG_CONFUSION_MATRIX = os.getenv("LOG_CONFUSION_MATRIX")

TOKENIZER = os.getenv("TOKENIZER")

DATA_VERSION = os.getenv("DATA_VERSION")
DATA_DIR = os.getenv("DATA_DIR")

BATCH_SIZE = int(os.getenv("BATCH_SIZE"))
LEARNING_RATE = float(os.getenv("LEARNING_RATE"))
NUM_EPOCH = int(os.getenv("NUM_EPOCH"))
NUM_EPOCH_ARGUMENT = int(os.getenv("NUM_EPOCH_ARGUMENT"))

MULT_DIM_MODEL = int(os.getenv("MULT_DIM_MODEL"))
MULT_NUM_HEAD = int(os.getenv("MULT_NUM_HEAD"))
MULT_NUM_LAYER = int(os.getenv("MULT_NUM_LAYER"))

SDIF_FEATURE_DIM = int(os.getenv("SDIF_FEATURE_DIM"))
SDIF_NUMLAYER_SELF_ATTENTION = int(os.getenv("SDIF_NUMLAYER_SELF_ATTENTION"))
SDIF_NUM_HEAD = int(os.getenv("SDIF_NUM_HEAD"))

COMET_API_KEY = os.getenv("COMET_API_KEY")
COMET_WORKSPACE = os.getenv("COMET_WORKSPACE")
COMET_PROJECT_NAME = os.getenv("COMET_PROJECT_NAME")


class Config:
    LOG_DATA_PATH = LOG_DATA_PATH
    LOG_MODEL_PATH = LOG_MODEL_PATH
    LOG_CONFUSION_MATRIX = LOG_CONFUSION_MATRIX

    TOKENIZER = TOKENIZER

    DATA_VERSION = DATA_VERSION
    DATA_DIR = DATA_DIR

    BATCH_SIZE = BATCH_SIZE
    LEARNING_RATE = LEARNING_RATE
    NUM_EPOCH = NUM_EPOCH
    NUM_EPOCH_ARGUMENT = NUM_EPOCH_ARGUMENT

    MULT_DIM_MODEL = MULT_DIM_MODEL
    MULT_NUM_HEAD = MULT_NUM_HEAD
    MULT_NUM_LAYER = MULT_NUM_LAYER

    SDIF_FEATURE_DIM = SDIF_FEATURE_DIM
    SDIF_NUMLAYER_SELF_ATTENTION = SDIF_NUMLAYER_SELF_ATTENTION
    SDIF_NUM_HEAD = SDIF_NUM_HEAD

    COMET_API_KEY = COMET_API_KEY
    COMET_WORKSPACE = COMET_WORKSPACE
    COMET_PROJECT_NAME = COMET_PROJECT_NAME
